name: Build and Execute Python Script
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11' ,'3.10']

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Exécution du script Python
        run: python main.py
      # - name: Installation des despendances
      #   run: pip install -r requirements.txt
      - name: Installation des dépendances
        run: pip install fastapi locust pytest uvicorn coverage httpx pytest-mock pytest-profiling pylint sqlalchemy pydantic
      - name: Exécution des tests
        run: |
          pytest
          coverage run -m pytest ; coverage xml
      - name: Get Coverage
        uses: orgoro/coverage@v3.1
        with: 
          coverageFile: 'coverage.xml'
          token: ${{ secrets.EPSI_TOKEN }}
          
